// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHqERjac4Rv-f8X4gXsT0XaylDms8BTdg',
    appId: '1:209324799297:web:fa8ba721b5d13c0b349dc0',
    messagingSenderId: '209324799297',
    projectId: 'two-easy-gym',
    authDomain: 'two-easy-gym.firebaseapp.com',
    storageBucket: 'two-easy-gym.firebasestorage.app',
    measurementId: 'G-ZJKL70MPVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPqp9GqQxpLkqCuPWhMhXAWhgbjplbj-o',
    appId: '1:209324799297:android:f4bd8dd452af49bd349dc0',
    messagingSenderId: '209324799297',
    projectId: 'two-easy-gym',
    storageBucket: 'two-easy-gym.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4xS7OE7LP_1P58tt9mBzvgbgGVZ_I7iE',
    appId: '1:209324799297:ios:bb689329639d0bb9349dc0',
    messagingSenderId: '209324799297',
    projectId: 'two-easy-gym',
    storageBucket: 'two-easy-gym.firebasestorage.app',
    iosBundleId: 'com.example.gymApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4xS7OE7LP_1P58tt9mBzvgbgGVZ_I7iE',
    appId: '1:209324799297:ios:bb689329639d0bb9349dc0',
    messagingSenderId: '209324799297',
    projectId: 'two-easy-gym',
    storageBucket: 'two-easy-gym.firebasestorage.app',
    iosBundleId: 'com.example.gymApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHqERjac4Rv-f8X4gXsT0XaylDms8BTdg',
    appId: '1:209324799297:web:f11ceb5cf3779f29349dc0',
    messagingSenderId: '209324799297',
    projectId: 'two-easy-gym',
    authDomain: 'two-easy-gym.firebaseapp.com',
    storageBucket: 'two-easy-gym.firebasestorage.app',
    measurementId: 'G-01G72MHVZT',
  );
}
