import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'firebase_options.dart'; // Auto-generated by FlutterFire CLI

// --- LOCAL IMPORTS ---
// Make sure these match your folder structure
import 'core/theme/app_colors.dart';
import 'features/dashboard/presentation/main_layout.dart';
import 'features/auth/presentation/login_screen.dart';

void main() async {
  // 1. Ensure Flutter bindings are ready before doing any async work
  WidgetsFlutterBinding.ensureInitialized();

  // 2. Initialize Firebase for the current platform (iOS/Android)
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // 3. Run the App
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '2Easy Gym App',
      debugShowCheckedModeBanner: false, // Removes the red "Debug" banner
      // 4. 🌗 AUTO-THEME: Listen to the phone's system settings (Light/Dark mode)
      themeMode: ThemeMode.system,

      // 5. ☀️ LIGHT THEME CONFIGURATION
      theme: ThemeData(
        brightness: Brightness.light,
        scaffoldBackgroundColor: AppColors.lightBackground,
        primaryColor: AppColors.primaryRed,

        // App Bar Style (Light)
        appBarTheme: const AppBarTheme(
          backgroundColor: AppColors.lightBackground,
          elevation: 0,
          centerTitle: true,
          iconTheme: IconThemeData(color: Colors.black),
          titleTextStyle: TextStyle(
            color: Colors.black,
            fontSize: 20,
            fontWeight: FontWeight.bold,
          ),
        ),

        // Card / Surface Style (Light)
        cardColor: AppColors.lightSurface,

        // Typography (Google Fonts)
        textTheme: GoogleFonts.poppinsTextTheme(ThemeData.light().textTheme),
        useMaterial3: true,
      ),

      // 6. 🌙 DARK THEME CONFIGURATION
      darkTheme: ThemeData(
        brightness: Brightness.dark,
        scaffoldBackgroundColor: AppColors.darkBackground,
        primaryColor: AppColors.primaryRed,

        // App Bar Style (Dark)
        appBarTheme: const AppBarTheme(
          backgroundColor: AppColors.darkBackground,
          elevation: 0,
          centerTitle: true,
          iconTheme: IconThemeData(color: Colors.white),
          titleTextStyle: TextStyle(
            color: Colors.white,
            fontSize: 20,
            fontWeight: FontWeight.bold,
          ),
        ),

        // Card / Surface Style (Dark)
        cardColor: AppColors.darkSurface,

        // Typography (Google Fonts)
        textTheme: GoogleFonts.poppinsTextTheme(ThemeData.dark().textTheme),
        useMaterial3: true,
      ),

      // 7. 🚪 THE AUTH GATE
      // This stream listens to Firebase. If a user is logged in, it returns
      // data (showing MainLayout). If they log out, data becomes null (showing LoginScreen).
      home: StreamBuilder<User?>(
        stream: FirebaseAuth.instance.authStateChanges(),
        builder: (context, snapshot) {
          // While Firebase is checking the user's status, show a loading spinner
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Scaffold(
              body: Center(
                child: CircularProgressIndicator(color: AppColors.primaryRed),
              ),
            );
          }

          // If we have a user, take them inside the app
          if (snapshot.hasData) {
            return const MainLayout();
          }

          // Otherwise, force them to log in
          return const LoginScreen();
        },
      ),
    );
  }
}
